# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twitter-lists-cli}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dwayne Litzenberger"]
  s.date = %q{2010-07-10}
  s.description = %q{A command-line client for manipulating large Twitter lists in the shell, shell scripts, etc.

Currently supports
------------------
- OAuth authentication
- Showing a users's followers/following
- Following and unfollowing users
- Showing, adding, and removing a members from a list
}
  s.email = %q{dlitz@dlitz.net}
  s.executables = ["twitter-auth", "twitter-follow", "twitter-following", "twitter-lists"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "VERSION.yml",
     "bin/twitter-auth",
     "bin/twitter-follow",
     "bin/twitter-following",
     "bin/twitter-lists"
  ]
  s.homepage = %q{http://github.com/dlitz/twitter-lists-cli}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Command-line client for manipulating Twitter lists.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<twitter>, ["~> 0.9.5"])
    else
      s.add_dependency(%q<twitter>, ["~> 0.9.5"])
    end
  else
    s.add_dependency(%q<twitter>, ["~> 0.9.5"])
  end
end

